stages:
  - build
  - test
  - documentation
  - publish

variables:
  MARVIN_BUILDNUMBER: "$CI_PIPELINE_ID"
  MARVIN_BRANCH: "$CI_COMMIT_REF_NAME"
  MARVIN_BUILD_CONFIG: "Release"
  MARVIN_OPTIMIZE_CODE: "false"

cache:
  paths:
    - packages

Build: 
  stage: build
  tags:
    - msbuild16
    - powershell
  script:
    - .\build.ps1 -SetAssemblyVersion -Build -Pack
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Packages'
      - 'src/StartProject/bin/$MARVIN_BUILD_CONFIG'

SmokeTests: 
  stage: test
  tags:
    - msbuild16
    - postgres
    - powershell
  script: .\build.ps1 -SmokeTests  

UnitTests: 
  stage: test
  tags:
    - msbuild16
    - powershell
  script: .\build.ps1 -UnitTests 
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Tests' 
  
IntegrationTests: 
  stage: test
  tags:
    - msbuild16
    - powershell
  script: .\build.ps1 -IntegrationTests
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Tests' 

SystemTests: 
  stage: test
  tags:
    - msbuild16
    - powershell
  script: .\build.ps1 -SystemTests
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Tests' 
      
GenerateDocs:
  stage: documentation
  tags:
    - msbuild16
    - powershell
  script: 
    - .\build.ps1 -CoverReport -GenerateDocs 
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Documentation'

PublishDocs: 
  stage: publish
  script: 'echo "Creating package of all precedence stages!"'
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/'

PublishPackages: 
  stage: publish
  tags:
    - msbuild16
    - powershell
  script: 
    - .\build.ps1 -Publish
  only: 
    - dev@marvin/MarvinPlatform