stages:
  - build
  - test
  - documentation
  - publish

Build: 
  stage: build
  tags:
    - vs2015
  script:
    - .\build.ps1 -Build

SmokeTests: 
  stage: test
  script: .\build.ps1 -Build -SmokeTests  
  tags:
    - vs2015
    - postgres

Tests: 
  stage: test
  script: .\build.ps1 -Build -UnitTests -IntegrationTests
  tags:
    - vs2015

SystemTests: 
  stage: test
  script: .\build.ps1 -Build -SystemTests
  tags:
    - vs2015

Documentation:
  tags:
    - vs2015
  stage: documentation
  script: .\build.ps1 -Build -GenerateDocs
  only: 
    - master@marvinplatform/MarvinPlatform

Publish: 
  tags:
    - vs2015
    - nuget
  stage: publish
  script: .\build.ps1 -SetAssemblyVersion -Build -BuildNumber $($env:CI_JOB_ID + 363) -Pack -Publish
  only: 
    - master@marvinplatform/MarvinPlatform