stages:
  - build-maintenance
  - build
  - test
  - documentation
  - publish

variables:
  MARVIN_BUILDNUMBER: "$CI_PIPELINE_ID"
  MARVIN_BRANCH: "$CI_COMMIT_REF_NAME"
  MARVIN_BUILD_CONFIG: "Release"
  MARVIN_OPTIMIZE_CODE: "false"

cache:
  paths:
    - packages

BuildMaintenance:
  image: dockerregistry.europe.phoenixcontact.com/node:9.5
  tags:
    - docker
  stage: build-maintenance
  cache:
    paths:
    - src/Marvin.Runtime.Maintenance.Web.UI/node_modules/
  script:
    - bash -x ./Build.sh -p=${MARVIN_BUILDNUMBER}
    - npm config set registry http://dockerregistry.europe.phoenixcontact.com/repository/pxc-npm-proxy/
    - npm config set strict-ssl false --global
    - npm config set https-proxy '${HTTP_PROXY}' --global
    - npm config set proxy '${HTTP_PROXY}' --global
    - cd src/Marvin.Runtime.Maintenance.Web.UI
    - npm run build
    - mkdir -p ../../artifacts/Maintenance.Web
    - cp -R dist/* ../../artifacts/Maintenance.Web/
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Maintenance.Web'
      - 'src/Marvin.Runtime.Maintenance.Web.UI/dist'

Build: 
  stage: build
  tags:
    - msbuild16
    - powershell
  script:
    - .\build.ps1 -SetAssemblyVersion -Build -Pack
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Packages'
      - 'src/StartProject/bin/$MARVIN_BUILD_CONFIG'

SmokeTests: 
  stage: test
  tags:
    - msbuild16
    - postgres
    - powershell
  script: .\build.ps1 -SmokeTests  

UnitTests: 
  stage: test
  tags:
    - msbuild16
    - powershell
  script: .\build.ps1 -UnitTests 
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Tests' 
  
IntegrationTests: 
  stage: test
  tags:
    - msbuild16
    - powershell
  script: .\build.ps1 -IntegrationTests
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Tests' 

SystemTests: 
  stage: test
  tags:
    - msbuild16
    - powershell
  script: .\build.ps1 -SystemTests
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Tests' 
      
GenerateDocs:
  stage: documentation
  tags:
    - msbuild16
    - powershell
  script: 
    - .\build.ps1 -CoverReport -GenerateDocs 
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/Documentation'

PublishDocs: 
  stage: publish
  script: 'echo "Creating package of all precedence stages!"'
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'artifacts/'

PublishPackages: 
  stage: publish
  tags:
    - msbuild16
    - powershell
  script: 
    - .\build.ps1 -Publish
  only: 
    - dev@marvin/MarvinPlatform