stages:
  - build
  - test
  - documentation
  - publish

variables:
  MARVIN_BUILDNUMBER: "$CI_PIPELINE_ID"
  MARVIN_BRANCH: "$CI_COMMIT_REF_NAME"
  MARVIN_BUILD_CONFIG: "Release"
  MARVIN_OPTIMIZE_CODE: "false"

Build: 
  stage: build
  tags:
    - vs2015
  script:
    - .\build.ps1 -SetAssemblyVersion -Build -Pack
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'Artifacts\Packages'

SmokeTests: 
  stage: test
  script: .\build.ps1 -Build -SmokeTests  
  tags:
    - vs2015
    - postgres

CoverTests: 
  stage: test
  script: .\build.ps1 -Build -UnitTests -IntegrationTests
  tags:
    - vs2015
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'Artifacts\Tests' 

GenerateDocs:
  tags:
    - vs2015
  stage: documentation
  script: 
    - .\build.ps1 -GenerateDocs
    - 'xcopy /s /i Documentation\_site\* Artifacts\Documentation'
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'Artifacts\Documentation'

PublishDocs: 
  stage: publish
  script: 'echo "Creating package of all precedence stages!"'
  artifacts:
    expire_in: 1 hrs
    paths:
      - 'Artifacts\'

PublishPackages: 
  tags:
    - vs2015
    - nuget
  stage: publish
  script: 
    - .\build.ps1 -Publish
  only: 
    - master@marvinplatform/MarvinPlatform