name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: 
      - dev
      - future
    tags:
      - v[0-9]+.[0-9]+.[0-9]+ # Matches all semantic versioning tags with major, minor, patch
  pull_request:
    branches: 
      - dev
      - future

env:
  MORYX_OPTIMIZE_CODE: "false"
  MORYX_BUILD_CONFIG: "Release"
  MORYX_BUILDNUMBER: ${{github.run_number}}
  dotnet_sdk_version: '7.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  Build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet_sdk_version }}

      - name: Build
        shell: pwsh
        run: ./Build.ps1 -Build -Pack

      - name: Upload package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: artifacts/Packages/
          retention-days: 1

