name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ master ]

env:
  MARVIN_OPTIMIZE_CODE: "false"
  MARVIN_BUILD_CONFIG: "Release"
  MARVIN_BUILDNUMBER: $GITHUB_RUN_NUMBER
  MARVIN_BRANCH: "master"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2

    - name: Build
      shell: pwsh
      run: ./Build.ps1 -SetAssemblyVersion

    - name: Build
      shell: pwsh
      run: ./Build.ps1 -Build -Pack

    - name: Pack packages
      shell: pwsh
      run: ./Build.ps1 -Pack