name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ master ]

env:
  MARVIN_OPTIMIZE_CODE: "false"
  MARVIN_BUILD_CONFIG: "Release"
  MARVIN_BUILDNUMBER: ${{github.run_number}}
  MARVIN_BRANCH: ${{github.ref}}
  MARVIN_CODECOV_SECRET: ${{secrets.CODECOV_TOKEN}}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2

    - name: Set assembly versions
      shell: pwsh
      run: ./Build.ps1 -SetAssemblyVersion

    - name: Build
      shell: pwsh
      run: ./Build.ps1 -Build

    - name: Pack packages
      shell: pwsh
      run: ./Build.ps1 -Pack

    - name: Upload package artifacts
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: artifacts/Packages
  test:
    needs: [build]
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
        
        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1
        
        - name: Setup NuGet.exe
          uses: NuGet/setup-nuget@v1.0.2

        - name: UnitTests
          shell: pwsh
          run: ./Build.ps1 -UnitTests -IntegrationTests

        - name: Cover Report
          shell: pwsh
          run: ./Build.ps1 -CoverReport

        - name: Upload test results
          uses: actions/upload-artifact@v1
          with:
            name: test-results
            path: artifacts/Tests